# Generated by Django 3.2.9 on 2021-12-12 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_accesslevel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
