# Generated by Django 3.2.9 on 2021-12-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_alter_accesslevel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthistory',
            name='request_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
